### PR TITLE
 Modify cisco-poap.py to use /api/current instead of /api/1.1

### PR DESCRIPTION
**Pull request by pengz1**
Modify cisco-poap.py to use /api/current instead of /api/1.1

### CODE REVIEW

**Comment by pengz1** [comment]
@yyscamper @iceiilin @sunnyqianzhang @lanchongyizu

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by sunnyqianzhang** [comment]
:+1:

**Pull request merged**
