### PR TITLE
Remove convenience binaries

### PR DESCRIPTION
**Pull request by heckj**
removing the bootloader binaries from on-tftp. These can be regenerated from the on-imagebuilder repository, and are stashed in bintray now for access and rebuilding them as that repository is updated. The bintray binaries are used in our vagrant setup.

@davidzuhn @johren this will have a downstream impact on your package based installations - as I don't think we otherwise had a copy of the ipxe boot loaders in a package that will get installed.

### CODE REVIEW

**Comment by benbp** [comment]
Off come the training wheels.

:+1:

**Comment by benbp** [comment]
Is it useful to have a .gitkeep in the static/tftp directory?

**Comment by heckj** [comment]
@benbp oh, duh- yeah - that would be good. Will add

**Comment by jlongever** [comment]
+1

**Pull request merged**
