### PR TITLE
fix code coverage badge to point to on-tftp

### PR DESCRIPTION
**Pull request by tldavies**

### CODE REVIEW

**Comment by tldavies** [comment]
@benbp @rolandpoulter @davequick @RackHD/corecommitters

**Comment by benbp** [comment]
Is this local to this repo, or is this copy/paste error in every one?

**Comment by tldavies** [comment]
this is just this one.

**Comment by benbp** [comment]
:+1:

**Comment by heckj** [comment]
+1

**Comment by DavidjohnBlodgett** [comment]
:+1:

**Pull request merged**
