### PR TITLE
ODR 220: Add Sleep of 10s to monorail ipxe 

### PR DESCRIPTION
**Pull request by keedya**
Monorail.ipxe built with the EMBED script that includes the sleep

### CODE REVIEW

**Comment by keedya** [comment]
@jfrey @benbp @zyoung51 @jlongever

**Comment by zyoung51** [comment]
:+1:

**Comment by jlongever** [comment]
@miramm did this fix your problem?

**Comment by miramm** [comment]
Yes, it fixes the problem.

**Comment by miramm** [comment]
FYI.. commenting around the 10 seconds delay and fixed from Ben. I grabbed this comment from ODR-235. 

Mirambeaux, Marcos added a comment - 31/Oct/15 5:56 PM - edited
I setup a new ova machine and replaced the monorail.ipxe with this version and tried the fix 3x and it worked each time. 
Here's what I noticed:
The nodes tried to get the profiles but it failed, then it tried a second time and it failed then the node did a power cycle after the second try and it got discovered without manual intervention. The delay causes the node to try a second time and gave-up and reboots, causing the node to be discovered during the second reboot. I added two screenshots of the retries. 
Conclusion: rewording the conclusion- this partially works but only because the hardware itself reboot probably due to a watchdog for taking too long and on the second time it gets discovered.

**Pull request merged**
