### PR TITLE
build refactor

### PR DESCRIPTION
**Pull request by ytjohn**
Moves the commands out of travis-ci and into shell scripts that can be executed by any build system.

### CODE REVIEW

**Comment by rolandpoulter** [comment]
Can you update the `.dockerignore` file to exclude the `extra/` directory?

**Comment by jlongever** [comment]
jenkins, test this please

**Comment by ytjohn** [comment]
.dockerignore updated

**Comment by anhou** [comment]
test this please

**Comment by benbp** [comment]
👍

**Comment by anhou** [comment]
:+1:

**Comment by benbp** [comment]
@ytjohn so I assume this may need the same update as on-dhcp-proxy? I'm hesitant to merge it even though it passes given the issues we saw.

**Comment by ytjohn** [comment]
You are correct. I'll update the pr with the correct adjustments

**Comment by ytjohn** [comment]
make-deb.sh updated to match fixes from on-dhcp-proxy.

https://github.com/RackHD/on-dhcp-proxy/pull/35

**Pull request merged**
