### PR TITLE
on-2917 - Get POAP workflows operation in RackHD 2.0+ for the Cisco switches

### PR DESCRIPTION
**Pull request by larry-dean**
* Extend logs
* Correct imports

### CODE REVIEW

**Comment by larry-dean** [comment]
@RackHD/corecommitters @johren

**Comment by jlongever** [comment]
test this please

**Comment by larry-dean** [comment]
@RackHD/corecommitters

**Comment by anhou** [comment]
:+1:

**Comment by anhou** [comment]
@larry-dean  I also submit PR https://github.com/RackHD/on-tftp/pull/50 to refine the codes. I'll rebase after this PR merged.

**Comment by johren** [comment]
+1

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
